### ISSUE TITLE
Bald leather armor frame issue

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Hero_Appearance#2]
The bald dude **leather armor** sledgehammer animation has 1 frame where a second head is visible in the middle of the image. I fixed it.

/Edit: The file needs to be renamed to _HMLTHRFA.frm

[nmlthrFA.zip](https://github.com/BGforgeNet/Fallout2_Hero_Appearance/files/6601023/nmlthrFA.zip)

**Comment by burner1024** [comment]
Added, thank you.
