### ISSUE TITLE
Hero Apperance buttons are not showing up.

### ISSUE THREAD

**Issue by Circe1337** [BGforgeNet/Fallout2_Hero_Appearance#3]
![apperance buttons](https://user-images.githubusercontent.com/95681620/148646039-b362c03f-1389-43b1-aed6-45cd86645510.jpg)

I can not change my hero appearance because the buttons to do it are not in the UI oddly. I am on Fallout 2 restoration patch version 25.

**Comment by burner1024** [comment]
how did you install it?

**Comment by Circe1337** [comment]
I extracted it into the game files.

**Comment by burner1024** [comment]
Did you use exe? Zip?
It doesn't look that it's installed correctly.

**Comment by Circe1337** [comment]
I used the ZIP. I'll try using the exa again.

**Comment by Circe1337** [comment]
Do you mean the unoffical patch? I used the exe to install the patch.

**Comment by Circe1337** [comment]
I have used now extracted the zip over the installation and nothing has changed.

**Comment by burner1024** [comment]
Unofficial patch and restoration project are two different things. Which one did you use?

**Comment by Circe1337** [comment]
Unofficial Patch
![image](https://user-images.githubusercontent.com/95681620/148680169-749852a8-4884-414b-9b8a-3286f9a47e8a.png)

**Comment by burner1024** [comment]
Well, UPU doesn't include Hero Appearance.

**Comment by Circe1337** [comment]
Ah that would explain it, though the notes on both the unofficial patch and the hero mode say that they hero appearance mod is compatible

**Comment by burner1024** [comment]
It is compatible, but not included. It is included with RPU.
For UPU, you can install HA manually as described in the readme.
I think that concludes this, if you run into any other problems, feel free to open issues in the corresponding repos.

**Comment by Circe1337** [comment]
![image](https://user-images.githubusercontent.com/95681620/148680698-1c076d58-a2e4-46d1-8ca0-4beaa67b0215.png)
So I have the files in the mod folder but I am unable to select anything but the Indian appearance.

**Comment by burner1024** [comment]
Did you enable the setting in ddraw.ini?

**Comment by Circe1337** [comment]
Yes it is set to 1

**Comment by burner1024** [comment]
Given that you used exe, then zip, I'd try a fresh installation from scratch - F2, UPU and HA.

**Comment by Circe1337** [comment]
I worked it out, Its because I installed HA into the mods folder and not the main dirct. Thanks

**Comment by burner1024** [comment]
Yes, unfortunately HA is different from other mods and should be extracted into main dir.
